#Esse é um arquivo teste para verificarmos como funciona o controle de versão
#do RStudio integrado com Git.

# Dummy...Dummy...Dummy...Dummy...Dummy...Dummy...Dummy...Dummy...Dummy...
# Dummy...Dummy...Dummy...Dummy...Dummy...Dummy...
# Dummy...Dummy...Dummy...